services:
  fhir-converter:
    image: ghcr.io/cdcgov/phdi/fhir-converter:latest
    pull_policy: always
    platform: linux/amd64
    container_name: ecr-parser-fhir-converter
    ports:
      - "8082:8080"
    networks:
      - dibbs_network

  message-parser:
    image: ghcr.io/cdcgov/phdi/message-parser:latest
    pull_policy: always
    platform: linux/amd64
    container_name: ecr-parser-message-parser
    ports:
      - "8085:8080"
    networks:
      - dibbs_network

networks:
  dibbs_network:
    driver: bridge
